# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    paths:
    - "**/*.go"
  pull_request:

jobs:

  lint:
    runs-on: ubuntu-latest
    name: Linters for Go
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

    - name: Lint & ver
      run: make lint

  tests:
    runs-on: ubuntu-latest
    name: Unit tests on Go ${{ matrix.go }} / ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.18', '1.19', '1.20' ]
        platform: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

    - name: Run unit test
      run: make test
